/**
 * generated by Xtext
 */
package org.palladiosimulator.pcm.pcmstoex.serializer;

import org.palladiosimulator.pcm.pcmstoex.serializer.AbstractPCMStoExSyntacticSequencer;

@SuppressWarnings("all")
public class PCMStoExSyntacticSequencer extends AbstractPCMStoExSyntacticSequencer {
}
