<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sourcecodedecorator"
    nsURI="http://sdq.ipd.uka.de/PalladioComponentModel/SourceCodeDecorator/1.0" nsPrefix="sourcecodedecorator">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="&lt;p>&#xD;&#xA;    Trace&amp;nbsp;Link&amp;nbsp;Model. The model comprises various PCM and GAST decorators:&#xD;&#xA;&lt;/p>&#xD;&#xA;&lt;p>&#xD;&#xA;    Connects PCM, GAST, Measuring&amp;nbsp;and Logging Data.&#xD;&#xA;&lt;/p>"/>
  </eAnnotations>
  <eSubpackages name="PCMLinkRepository" nsURI="http:///SourceCodeDecorator/PCMLinkRepository.ecore"
      nsPrefix="SourceCodeDecorator.PCMLinkRepository">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Repository Package for LoggerLink and GastPCMLink Packages. Contains the core root element of both other packages."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="PCMLinkRepository" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="loggingPositionLinks"
          ordered="false" upperBound="-1" eType="#//loggerlink/LoggingPositionIdLink"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="internalActionLinks"
          ordered="false" upperBound="-1" eType="#//GastPcmLink/InternalActionLink"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputParameterLinks"
          ordered="false" upperBound="-1" eType="#//GastPcmLink/ParameterLink" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="loggerlink" nsURI="http:///SourceCodeDecorator/loggerLink.ecore"
      nsPrefix="SourceCodeDecorator.loggerLink">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The LoggerLink package is required for associating&amp;nbsp;logging data to pcm entities&amp;nbsp;only. It does not decorate the&#xD;&#xA;source code."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="BeforeReturnValueLoggingPositionLink"
        eSuperTypes="#//loggerlink/OutputLoggingPositionLink">
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkedSetVariableAction"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/SetVariableAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedFunctionOfSurroundingSeff"
          ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Function"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterLink" ordered="false"
          upperBound="-1" eType="#//GastPcmLink/ParameterLink" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OutputLoggingPositionLink" abstract="true"
        eSuperTypes="#//loggerlink/LoggingPositionIdLink"/>
    <eClassifiers xsi:type="ecore:EClass" name="BeforeExternalCallLoggingPositionLink"
        eSuperTypes="#//loggerlink/OutputLoggingPositionLink">
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkedExternalCallAction"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/ExternalCallAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="calledFunction" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Function"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterLink" ordered="false"
          upperBound="-1" eType="#//GastPcmLink/ParameterLink" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodCallLoggingPositionLink" eSuperTypes="#//loggerlink/InputLoggingPositionLink">
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkedServiceEffectSpecification"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/ResourceDemandingSEFF"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedFunction" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Function"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterLinks" ordered="false"
          upperBound="-1" eType="#//GastPcmLink/ParameterLink" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InputLoggingPositionLink" abstract="true"
        eSuperTypes="#//loggerlink/LoggingPositionIdLink"/>
    <eClassifiers xsi:type="ecore:EClass" name="AfterExternalCallLoggingPositionLink"
        eSuperTypes="#//loggerlink/InputLoggingPositionLink">
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkedExternalCallAction"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/ExternalCallAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="calledFunction" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Function"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterLink" ordered="false"
          upperBound="-1" eType="#//GastPcmLink/ParameterLink" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BranchLoggingPositionLink" eSuperTypes="#//loggerlink/OutputLoggingPositionLink">
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkedGuardedBranchTransition"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/GuardedBranchTransition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="branchStatement" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//statements/Statement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoopLoggingPositionLink" eSuperTypes="#//loggerlink/OutputLoggingPositionLink">
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkedLoopAction" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/LoopAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="loopStatement" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//statements/Statement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoggingPositionIdLink" abstract="true"
        eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="loggingPositionId" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="GastPcmLink" nsURI="http:///SourceCodeDecorator/GastPcmLink.ecore"
      nsPrefix="SourceCodeDecorator.GastPcmLink">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Trace link package for mapping&amp;nbsp;GAST model elements and reverse engineered PCM model elements."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="InternalActionLink" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkedInternalAction"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/InternalAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="internalActionStatements"
          ordered="false" lowerBound="1" upperBound="-1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//statements/Statement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterLink" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkedParameter" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//repository/Parameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//variables/FormalParameter"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="rawResourceDemandCounts" nsURI="http:///SourceCodeDecorator/rawResourceDemandCounts.ecore"
      nsPrefix="SourceCodeDecorator.rawResourceDemandCounts">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Decorator&amp;nbsp;models&amp;nbsp;which&amp;nbsp;annotate&amp;nbsp;raw&amp;nbsp;resource&amp;nbsp;demands&amp;nbsp;to&amp;nbsp;AbstractInternalControlFlowActions."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="RawResourceDemandsLink" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="internalAction" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/AbstractInternalControlFlowAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bytecodeMonitoringRuns"
          ordered="false" upperBound="-1" eType="#//rawResourceDemandCounts/BytecodeMonitoringRun"
          eOpposite="#//rawResourceDemandCounts/BytecodeMonitoringRun/rawResourceDemandsLink"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BytecodeMonitoringRun" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="measuredCounts" ordered="false"
          upperBound="-1" eType="#//rawResourceDemandCounts/MeasuredCount" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputParameterCharacterisations"
          ordered="false" upperBound="-1" eType="#//rawResourceDemandCounts/MeasuredCharacterisationValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="environmentCharacterisation"
          ordered="false" eType="#//rawResourceDemandCounts/EnvironmentCharacterisation"
          eOpposite="#//rawResourceDemandCounts/EnvironmentCharacterisation/bytecodeMonitoringRuns"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rawResourceDemandsLink"
          ordered="false" lowerBound="1" eType="#//rawResourceDemandCounts/RawResourceDemandsLink"
          eOpposite="#//rawResourceDemandCounts/RawResourceDemandsLink/bytecodeMonitoringRuns"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MeasuredCount" abstract="true" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;p>&#xD;&#xA;    A&amp;nbsp;measured value for a conrete combination of parameters and signature.&#xD;&#xA;&lt;/p>&#xD;&#xA;&lt;p>&#xD;&#xA;    Can be: The number of execution of a single&amp;nbsp;bytecode (only bytecode signature set) or&lt;br />&#xD;&#xA;    number of method calls with a certain parameter set (e.g. 3x&amp;nbsp;doSth(int a, int b):&amp;nbsp;signature associated&#xD;&#xA;    and&amp;nbsp;parameter values specified (e.g. 0, 0)&#xD;&#xA;&lt;/p>"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="signature" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//repository/Signature"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterValues" ordered="false"
          upperBound="-1" eType="#//rawResourceDemandCounts/ParameterValue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterValue" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="describedParameter" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//repository/Parameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="measuredCharacterisationValue"
          ordered="false" upperBound="-1" eType="#//rawResourceDemandCounts/MeasuredCharacterisationValue"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MeasuredCharacterisationValue" abstract="true"
        eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="these measurement values will finally be mapped to EDP2"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredCharacterisation"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//repository/RequiredCharacterisation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnvironmentCharacterisation" abstract="true"
        eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="e.g. settings of JVM or Garbage Collection"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bytecodeMonitoringRuns"
          ordered="false" upperBound="-1" eType="#//rawResourceDemandCounts/BytecodeMonitoringRun"
          eOpposite="#//rawResourceDemandCounts/BytecodeMonitoringRun/environmentCharacterisation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RawResourceDemandsRepository" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bytecodeMonitoringRuns"
          ordered="false" upperBound="-1" eType="#//rawResourceDemandCounts/BytecodeMonitoringRun"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rawResourceDemandsLinks"
          ordered="false" upperBound="-1" eType="#//rawResourceDemandCounts/RawResourceDemandsLink"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="environmentCharacterisations"
          ordered="false" upperBound="-1" eType="#//rawResourceDemandCounts/EnvironmentCharacterisation"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DoubleCharacterisationValue" eSuperTypes="#//rawResourceDemandCounts/MeasuredCharacterisationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LongCharacterisationValue" eSuperTypes="#//rawResourceDemandCounts/MeasuredCharacterisationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanCharacterisationValue" eSuperTypes="#//rawResourceDemandCounts/MeasuredCharacterisationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
