<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ProtocolPackage"
    nsURI="http:///PalladioCM/ProtocolPackage.ecore" nsPrefix="PalladioCM.ProtocolPackage">
  <eClassifiers xsi:type="ecore:EClass" name="Protocol" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocolTypeID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceCall" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature__ServiceCall"
        lowerBound="1" eType="ecore:EClass RepositoryPackage.ecore#//Signature"/>
  </eClassifiers>
</ecore:EPackage>
