<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ResourceTypePackage"
    nsURI="http:///PalladioCM/ResourceTypePackage.ecore" nsPrefix="PalladioCM.ResourceTypePackage">
  <eClassifiers xsi:type="ecore:EClass" name="ResourceType" abstract="true" eSuperTypes="PalladioCM.CorePackage.ecore#//Entity/Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="PassiveResourceType" eSuperTypes="#//ResourceType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingResourceType" eSuperTypes="#//ResourceType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableResourceTypes_ResourceRepository"
        upperBound="-1" eType="#//ResourceType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationLinkResourceType" eSuperTypes="#//ProcessingResourceType"/>
</ecore:EPackage>
