package edu.kit.ipd.sdq.simcomp.system.component;

import de.uka.ipd.sdq.pcm.usagemodel.EntryLevelSystemCall;
import edu.kit.ipd.sdq.simcomp.component.ISimulationComponent;
import edu.kit.ipd.sdq.simcomp.component.IUser;
import edu.kit.ipd.sdq.simcomp.system.events.SystemRequestProcessed;
import edu.kit.ipd.sdq.simcomp.system.events.SystemRequestStart;

/**
 * Represents a system simulation component which handles service calls
 * generated by an {@link IWorkload} simulation component.
 * 
 * @author Christoph Föhrdes
 */
public interface ISystem extends ISimulationComponent {

	/**
	 * List of simulation events triggered by this simulation component.
	 */
	@SuppressWarnings("rawtypes")
	public static Class[] componentEvents = new Class[] { 
		SystemRequestStart.class,
		SystemRequestProcessed.class
	};

	public void callService(IUser user, EntryLevelSystemCall call);

}
