
package mediastorews;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mediarepository.entities.DBID3v1;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-hudson-182-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MediastoreWeb", targetNamespace = "http://mediastorews/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MediastoreWeb {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<mediastorews.Dbid3V1>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryID3", targetNamespace = "http://mediastorews/", className = "mediastorews.QueryID3")
    @ResponseWrapper(localName = "queryID3Response", targetNamespace = "http://mediastorews/", className = "mediastorews.QueryID3Response")
    public List<DBID3v1> queryID3(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<byte[]>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadHTTP", targetNamespace = "http://mediastorews/", className = "mediastorews.DownloadHTTP")
    @ResponseWrapper(localName = "downloadHTTPResponse", targetNamespace = "http://mediastorews/", className = "mediastorews.DownloadHTTPResponse")
    public List<byte[]> downloadHTTP(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<byte[]>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryFileByField", targetNamespace = "http://mediastorews/", className = "mediastorews.QueryFileByField")
    @ResponseWrapper(localName = "queryFileByFieldResponse", targetNamespace = "http://mediastorews/", className = "mediastorews.QueryFileByFieldResponse")
    public List<byte[]> queryFileByField(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
