/*
 * generated by Xtext
 */
package org.palladiosimulator.pcm.pcmstoex.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.palladiosimulator.pcm.pcmstoex.services.PCMStoExGrammarAccess;

public class PCMStoExParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PCMStoExGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.palladiosimulator.pcm.pcmstoex.parser.antlr.internal.InternalPCMStoExParser createParser(XtextTokenStream stream) {
		return new org.palladiosimulator.pcm.pcmstoex.parser.antlr.internal.InternalPCMStoExParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ausdruck";
	}
	
	public PCMStoExGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PCMStoExGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
