/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.pcm.repository.validation;

import de.uka.ipd.sdq.pcm.core.entity.InterfaceRequiringEntity;

import de.uka.ipd.sdq.pcm.repository.Interface;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.pcm.repository.RequiredRole}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RequiredRoleValidator {
	boolean validate();

	boolean validateRequiredInterface__RequiredRole(Interface value);
	boolean validateRequiringEntity_RequiredRole(InterfaceRequiringEntity value);
}
