/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.pcm.usagemodel.validation;

import de.uka.ipd.sdq.pcm.usagemodel.ScenarioBehaviour;
import de.uka.ipd.sdq.pcm.usagemodel.Workload;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.pcm.usagemodel.UsageScenario}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UsageScenarioValidator {
	boolean validate();

	boolean validateWorkload_UsageScenario(Workload value);
	boolean validateScenarioBehaviour_UsageScenario(ScenarioBehaviour value);
}
