package de.uka.ipd.sdq.BySuite.utils;


/**
 * TODO document
 * @author Martin Krogmann
 * @author Michael Kuperberg
 * @since 0.1
 * @version 1.1
 */
public interface ICountingResultWriter {
	/** 
	 * @param cr CountingResult to write
	 * @param usePrevTimestamp
	 * @param prevTimestampToUse
	 * @return timestamp that is part of the file name 
	 * (if usePrevTimestamp==false, 
	 * the returned timestamp is internally generated by this method)
	 */
	public long writeResult(CountingResult cr,
			boolean usePrevTimestamp,
			long prevTimestampToUse);
}
