/*
 * generated by Xtext 2.24.0
 */
package org.palladiosimulator.pcm.stoex.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.embedded.IEditedResourceProvider;
import org.palladiosimulator.pcm.stoex.ui.dialog.StoExEditDialogFactory;
import org.palladiosimulator.pcm.stoex.ui.dialog.impl.StoExEditDialogFactoryImpl;
import org.palladiosimulator.pcm.stoex.ui.dialog.impl.StoexEditedResourceProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@SuppressWarnings("restriction")
public class PCMStoexUiModule extends AbstractPCMStoexUiModule {

	public PCMStoexUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
    public Class<? extends StoExEditDialogFactory> bindStoExEditDialogFactory() {
        return StoExEditDialogFactoryImpl.class;
    }

    public Class<? extends IEditedResourceProvider> bindIEditedResourceProvider() {
        return StoexEditedResourceProvider.class;
    }
}
