<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ExampleAnotationModel"
    nsURI="http:///ExampleAnotationModel.ecore" nsPrefix="ExampleAnotationModel">
  <eClassifiers xsi:type="ecore:EClass" name="MyDataValue" eSuperTypes="PalladioCM.ecore#//AnotationDataValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="myComplexValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
  </eClassifiers>
</ecore:EPackage>
