/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.pcm.seff.validation;

import de.uka.ipd.sdq.pcm.parameter.VariableUsage;

import de.uka.ipd.sdq.pcm.repository.Signature;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.pcm.seff.ExternalCallAction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExternalCallActionValidator {
	boolean validate();

	boolean validateCalledService_ExternalService(Signature value);
	boolean validateParameterUsage_ExternalCallAction(EList<VariableUsage> value);
	boolean validateOutputVariableUsage_ExternalCallAction(EList<VariableUsage> value);
}
