<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="resultdecorator" nsURI="http://palladiosimulator.org/PCM/ResultDecorator/1.0"
    nsPrefix="resultdecorator">
  <eClassifiers xsi:type="ecore:EClass" name="ResultDecoratorRepository" eSuperTypes="../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentResults_ResultDecoratorRepository"
        ordered="false" upperBound="-1" eType="#//repositorydecorator/ComponentResult"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="utilisationResults_ResultDecoratorRepository"
        ordered="false" upperBound="-1" eType="#//resourceenvironmentdecorator/UtilisationResult"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceResult_ResultDecoratorRepository"
        ordered="false" upperBound="-1" eType="#//repositorydecorator/ServiceResult"
        containment="true"/>
  </eClassifiers>
  <eSubpackages name="repositorydecorator" nsURI="http://palladiosimulator.org/PCM/ResultDecorator/Repository/1.0"
      nsPrefix="repositorydecorator">
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceProvidingRequiringEntityResults"
        eSuperTypes="#//repositorydecorator/ComponentResult">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceProvidingRequiringEntity_InterfaceProvidingRequiringEntityResult"
          ordered="false" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/InterfaceProvidingRequiringEntity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentResult" abstract="true" eSuperTypes="../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="normalisedResourceDemand"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="normalisedResponseTime"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageResourceDemand"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="meanResponseTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageNumberOfSentMessages"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AllocationContextResults" eSuperTypes="#//repositorydecorator/ComponentResult">
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContext_AllocationContextResult"
          ordered="false" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceResult" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Performance results of one service. The context of the resulst is defined by the concrete subclasses (e.g. service result per AllocationContext, etc.)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="meanResponseTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="throughput" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="serviceEffectSpecification_ServiceResult"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/ServiceEffectSpecification"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AllocationServiceResult" eSuperTypes="#//repositorydecorator/ServiceResult">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Performance results of one service within one AllocationContext. Thus, for one AllocationContext in the system there should only exist one AllocationServiceResult per ResultdecoratorRepostory (TODO: OCL constraint). In particular, this means that even if the system has several UsageScenarios, there is only one AllocationServiceResult."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContext_AllocationServiceResult"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="resourceenvironmentdecorator" nsURI="http://palladiosimulator.org/PCM/ResultDecorator/ResourceEnvironment/1.0"
      nsPrefix="resourceenvironmentdecorator">
    <eClassifiers xsi:type="ecore:EClass" name="LinkingResourceResults" eSuperTypes="#//resourceenvironmentdecorator/ActiveResourceUtilisationResult">
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkingResource_LinkingResourceResults"
          ordered="false" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourceenvironment/LinkingResource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActiveResourceUtilisationResult" abstract="true"
        eSuperTypes="#//resourceenvironmentdecorator/UtilisationResult">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="normalisedDemandedTime"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The demanded time relative to all demanded times (in the system or in the resource container?)"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="demandedTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The average time that each job requests from this active resource. "/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UtilisationResult" abstract="true"
        eSuperTypes="../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="normalisedResourceUtilisation"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The resource utilisation relative to all resource utilisations in this system."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="normalisedWaitTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The wait time relative to all resource utilisations in this system."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceUtilisation"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The resource utilisation of this resource between 0 and 1."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageWaitTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The average time that each job has to wait before (FIFO) or while (processor sharing) accessing the resource. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageQueueLength" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The average length of the queue at this resource. For processor sharing, this is the number of busy jobs - 1. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxQueueLength" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The maximum length of the queue at this resource that has been observed during a simulation or that has been analytically determined, if possible. For processor sharing, this is the maximum number of busy jobs - 1. "/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceContainerResults" eSuperTypes="#//resourceenvironmentdecorator/ActiveResourceUtilisationResult">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceContainer_ResourceContainerResults"
          ordered="false" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessingResourceSpecificationResult"
        eSuperTypes="#//resourceenvironmentdecorator/ActiveResourceUtilisationResult">
      <eStructuralFeatures xsi:type="ecore:EReference" name="processingResourceSpecification_ProcessingResourceSpecificationResult"
          ordered="false" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourceenvironment/ProcessingResourceSpecification"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PassiveResourceResult" eSuperTypes="#//resourceenvironmentdecorator/UtilisationResult">
      <eStructuralFeatures xsi:type="ecore:EReference" name="passiveResource_PassiveResourceResult"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//repository/PassiveResource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContext_PassiveResourceResult"
          ordered="false" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageHoldingTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
