<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RegEx">
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="distributionFunction" eType="#//DistributionFunction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="distributionFunctionFreq"
        eType="#//DistributionFunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Symbol" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alternative" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="altOne" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="altTwo" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probOne" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probTwo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pre" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="post" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inner" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reiterationDistribution"
        eType="#//DistributionFunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parallel" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskOne" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskTwo" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DistributionFunction">
    <eOperations name="makePow2Elements"/>
    <eOperations name="expandTo">
      <eParameters name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="add" eType="#//DistributionFunction">
      <eParameters name="df" eType="#//DistributionFunction"/>
    </eOperations>
    <eOperations name="scale" eType="#//DistributionFunction">
      <eParameters name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="multiply" eType="#//DistributionFunction">
      <eParameters name="df" eType="#//DistributionFunction"/>
    </eOperations>
    <eOperations name="addPoint">
      <eParameters name="point" eType="#//Complex"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" upperBound="-1"
        eType="#//Complex" defaultValueLiteral="" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFourierTransformed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Complex">
    <eOperations name="abs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="phase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="plus" eType="#//Complex">
      <eParameters name="b" eType="#//Complex"/>
    </eOperations>
    <eOperations name="minus" eType="#//Complex">
      <eParameters name="b" eType="#//Complex"/>
    </eOperations>
    <eOperations name="times" eType="#//Complex">
      <eParameters name="b" eType="#//Complex"/>
    </eOperations>
    <eOperations name="conjugate" eType="#//Complex"/>
    <eOperations name="reciprocal" eType="#//Complex"/>
    <eOperations name="divides" eType="#//Complex">
      <eParameters name="b" eType="#//Complex"/>
    </eOperations>
    <eOperations name="plus" eType="#//Complex">
      <eParameters name="a" eType="#//Complex"/>
      <eParameters name="b" eType="#//Complex"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="re" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="im" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
