<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="context"
    nsURI="http://sdq.ipd.uka.de/Context/1.0" nsPrefix="context">
  <eSubpackages name="computed_usage" nsURI="http://sdq.ipd.uka.de/Context/Usage/1.0"
      nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="ComputedUsageContext" eSuperTypes="../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="branchProbabilities_ComputedUsageContext"
          ordered="false" upperBound="-1" eType="#//computed_usage/BranchProbability"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="loopiterations_ComputedUsageContext"
          ordered="false" upperBound="-1" eType="#//computed_usage/LoopIteration"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContext_ComputedUsageContext"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="input_ComputedUsageContext"
          ordered="false" lowerBound="1" eType="#//computed_usage/Input" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="externalCallOutput_ComputedUsageContext"
          ordered="false" upperBound="-1" eType="#//computed_usage/ExternalCallOutput"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="externalCallInput_ComputedUsageContext"
          ordered="false" upperBound="-1" eType="#//computed_usage/ExternalCallInput"
          containment="true" eOpposite="#//computed_usage/ExternalCallInput/computedUsageContext_ExternalCallInput"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="output_ComputedUsageContext"
          ordered="false" lowerBound="1" eType="#//computed_usage/Output" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BranchProbability">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="branchtransition_BranchProbability"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/AbstractBranchTransition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoopIteration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="loopaction_LoopIteration"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/AbstractLoopAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specification_LoopIteration"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/PCMRandomVariable"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Input">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterChacterisations_Input"
          ordered="false" upperBound="-1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//parameter/VariableUsage"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalCallOutput">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterCharacterisations_ExternalCallOutput"
          ordered="false" upperBound="-1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//parameter/VariableUsage"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="externalCallAction_ExternalCallOutput"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/ExternalCallAction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalCallInput">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterCharacterisations_ExternalCallInput"
          ordered="false" upperBound="-1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//parameter/VariableUsage"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="externalCallAction_ExternalCallInput"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/ExternalCallAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="computedUsageContext_ExternalCallInput"
          ordered="false" lowerBound="1" eType="#//computed_usage/ComputedUsageContext"
          eOpposite="#//computed_usage/ComputedUsageContext/externalCallInput_ComputedUsageContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Output">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterCharacterisations_Output"
          ordered="false" upperBound="-1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//parameter/VariableUsage"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComputedUsage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="usageContexts_ComputedUsage"
          ordered="false" upperBound="-1" eType="#//computed_usage/ComputedUsageContext"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="computed_allocation" nsURI="http://sdq.ipd.uka.de/Context/Allocation/1.0"
      nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="ComputedAllocationContext" eSuperTypes="../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceDemands_ComputedAllocationContext"
          ordered="false" upperBound="-1" eType="#//computed_allocation/ResourceDemand"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usageContext_ComputedAllocationContext"
          ordered="false" lowerBound="1" eType="#//computed_usage/ComputedUsageContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContext_ComputedAllocationContext"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceDemand">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parametricResourceDemand_ResourceDemand"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/seff_performance/ParametricResourceDemand"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specification_ResourceDemand"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/PCMRandomVariable"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComputedAllocation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="computedAllocationContexts_ComputedAllocation"
          ordered="false" upperBound="-1" eType="#//computed_allocation/ComputedAllocationContext"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="aggregatedUsageContext" nsURI="http:///context/aggregatedUsageContext.ecore"
      nsPrefix="context.aggregatedUsageContext">
    <eClassifiers xsi:type="ecore:EClass" name="ServiceExecutionContext">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Stores context information for the execution of a service. The information is aggregated on the level of AssembyContexts and aggregates the calls to this service from different other components. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="globalExecutionFrequency"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Average frequency of executing this service when executing a UsageScenario. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContext_ServiceExecutionContext"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="describedSEFF_ServiceExecutionContext"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/ResourceDemandingSEFF"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedResourceDemands_ServiceExecutionContext"
          ordered="false" upperBound="-1" eType="#//aggregatedUsageContext/AggregatedResourceDemand"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usageScenario_ServiceExecutionContext"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//usagemodel/UsageScenario"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sentAggregatedCommunications_ServiceExecutionContext"
          ordered="false" upperBound="-1" eType="#//aggregatedUsageContext/AggregatedCommunication"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The AggregatedCommunication in which this service is the sender. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receivedAggregatedCommunication_AggregatedCommunication"
          ordered="false" upperBound="-1" eType="#//aggregatedUsageContext/AggregatedCommunication"
          eOpposite="#//aggregatedUsageContext/AggregatedCommunication/receiver_AggregatedCommunication">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The AggregatedCommunication in which this service is the receiver. "/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AggregatedResourceDemand">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregatedResourceDemand"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The aggregated resource demand of this service, where the single resource demands are weighted by their frequency (including the frequency of the service itself) and averaged. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceType_AggregatedResourceDemand"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourcetype/ResourceType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AggregatedCommunication">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AggregatedCommunication holds the communication information for the communication of two services, where the owning service is the sender and the referenced receiver_AggregatedCommunication is the receiver.&#xD;&#xA;&#xD;&#xA;If two services A and B communicate in different roles with each other, i.e. sometimes A calls B, sometimes B calls A, there will be two AggregatedCommunication, one with A as the sender, one with B as the sender. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageMessageSize" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageMessageFrequency"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Average  message frequency of this communication when executing a UsageScenario. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receiver_AggregatedCommunication"
          ordered="false" lowerBound="1" eType="#//aggregatedUsageContext/ServiceExecutionContext"
          eOpposite="#//aggregatedUsageContext/ServiceExecutionContext/receivedAggregatedCommunication_AggregatedCommunication">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The receiver of this communication."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usedCommunicationLinkResourceSpecification_AggregatedCommunication"
          ordered="false" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourceenvironment/CommunicationLinkResourceSpecification">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The usedCommunicationLinkResourceSpecification is null if this is a local communication. "/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComputedAggregatedUsage">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Combines the ServiceExecutionContexts from one UsageScenario. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="serviceExecutionContexts_ComputedAggregatedUsage"
          ordered="false" upperBound="-1" eType="#//aggregatedUsageContext/ServiceExecutionContext"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
