<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simucomstatus"
    nsURI="http://sdq.ipd.uka.de/SimuComStatus/1.0" nsPrefix="simucomstatus">
  <eClassifiers xsi:type="ecore:EClass" name="SimuComStatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processStatus" ordered="false"
        lowerBound="1" eType="#//SimulatedProcesses" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceStatus" ordered="false"
        lowerBound="1" eType="#//SimulatedResources" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentSimulationTime"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedProcesses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processes" ordered="false"
        upperBound="-1" eType="#//Process" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentAction" ordered="false"
        lowerBound="1" eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processStartTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionStartTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionDuration" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedResources">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeResources" ordered="false"
        upperBound="-1" eType="#//ActiveResouce" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passiveResources" ordered="false"
        upperBound="-1" eType="#//PassiveResource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActiveResouce">
    <eStructuralFeatures xsi:type="ecore:EReference" name="waitingDemands" ordered="false"
        upperBound="-1" eType="#//WaitForDemand" eOpposite="#//WaitForDemand/resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaitForDemand" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="demand" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" ordered="false"
        lowerBound="1" eType="#//ActiveResouce" eOpposite="#//ActiveResouce/waitingDemands"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassiveResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="waitingProcesses" ordered="false"
        upperBound="-1" eType="#//WaitForAcquire" eOpposite="#//WaitForAcquire/resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialResourceCount" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourcesAvailable" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaitForAcquire" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" ordered="false"
        lowerBound="1" eType="#//PassiveResource" eOpposite="#//PassiveResource/waitingProcesses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaitForDelay" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
