/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.featureconfig.validation;

import org.eclipse.emf.ecore.EObject;


/**
 * A sample validator interface for {@link de.uka.ipd.sdq.featureconfig.FeatureConfig}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeatureConfigValidator {
	boolean validate();

	boolean validateReferencedObject(EObject value);

}
