/*
 * generated by Xtext
 */
package org.palladiosimulator.pcm.pcmstoex;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PCMStoExRuntimeModule extends org.palladiosimulator.pcm.pcmstoex.AbstractPCMStoExRuntimeModule {

}
