/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.context.usage.validation;

import de.uka.ipd.sdq.pcm.seff.AbstractBranchTransition;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.context.usage.BranchProbability}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BranchProbabilityValidator {
	boolean validate();

	boolean validateProbability(double value);
	boolean validateBranchtransition_BranchProbability(AbstractBranchTransition value);
}
