/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.context.usage.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.context.usage.UsageContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UsageContextValidator {
	boolean validate();

	boolean validateBranchprobabilities_UsageContext(EList value);
	boolean validateLoopiterations_UsageContext(EList value);
	boolean validateActualParameterUsage_UsageContext(EList value);
}
