/*
 * generated by Xtext
 */
package org.palladiosimulator.pcm.pcmstoex;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PCMStoExUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.palladiosimulator.pcm.pcmstoex.ui.internal.PCMStoExActivator.getInstance().getInjector("org.palladiosimulator.pcm.pcmstoex.PCMStoEx");
	}
	
}
