<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RepositoryPackage"
    nsURI="http:///PalladioCM/RepositoryPackage.ecore" nsPrefix="PalladioCM.RepositoryPackage">
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterModifier">
    <eLiterals name="none"/>
    <eLiterals name="in" value="1"/>
    <eLiterals name="out" value="2"/>
    <eLiterals name="inout" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signature">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ParameterNamesHaveToBeUniqueForASignature"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters__Signature"
        upperBound="-1" eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returntype__Signature"
        lowerBound="1" eType="#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exceptions__Signature"
        upperBound="-1" eType="#//ExceptionType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype__Parameter" lowerBound="1"
        eType="#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier__Parameter" lowerBound="1"
        eType="#//ParameterModifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentDataType__DataType"
        eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExceptionType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exceptionName" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exceptionMessage" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true" eSuperTypes="PalladioCM.CorePackage.ecore#//Entity/Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredRole" eSuperTypes="#//Role">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterface__RequiredRole"
        lowerBound="1" eType="#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="PalladioCM.CorePackage.ecore#//Entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noProtocolTypeIDUsedTwice SignaturesHaveToBeUniqueForAnInterface"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signatures__Interface"
        upperBound="-1" eType="#//Signature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentInterface__Interface"
        upperBound="-1" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anchestorInterfaces" upperBound="-1"
        eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protocols__Interface" upperBound="-1"
        eType="ecore:EClass ProtocolPackage.ecore#//Protocol" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredDelegationConnector" eSuperTypes="#//DelegationConnector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="innerAndOuterRoleNeedToHaveDifferentContextIDs InnerContainingComponentEqualOuterRequiringComponent"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerRequiredRole_RequiredDelegationConnector"
        lowerBound="1" eType="#//RequiredRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outerRequiredRole_RequiredDelegationConnector"
        lowerBound="1" eType="#//RequiredRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childComponentContext_RequiredDelegationConnector"
        lowerBound="1" eType="#//ChildComponentContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelegationConnector" abstract="true"
      eSuperTypes="PalladioCM.CorePackage.ecore#//Connectors/Connector"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChildComponentContext" eSuperTypes="PalladioCM.CorePackage.ecore#//Entity/Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulatedComponent_ChildComponentContext"
        lowerBound="1" eType="#//ProvidesComponentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidesComponentType" eSuperTypes="PalladioCM.CorePackage.ecore#//Entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="AtLeastOneInterfaceHasToBeProvidedByAUsefullProvidesComponentType AtLeastOneInterfaceHasToBeProvidedOrRequiredByAUsefullCompleteComponentType"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedRoles__ProvidesComponentType"
        upperBound="-1" eType="#//ProvidedRole" containment="true" eOpposite="#//ProvidedRole/providingComponent__ProvidedRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRoles_ProvidesComponentType"
        upperBound="-1" eType="#//RequiredRole" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedRole" eSuperTypes="#//Role">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterface__ProvidedRole"
        lowerBound="1" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providingComponent__ProvidedRole"
        lowerBound="1" eType="#//ProvidesComponentType" eOpposite="#//ProvidesComponentType/providedRoles__ProvidesComponentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="GrantFirstClassEntityTypeCompositeComponent GrantFirstClassEntityTypeProvidesComponentType GrantFirstClassEntityTypeCompleteComponentType GrantFirstClassEntityTypeImplementationComponentType GrantFirstClassEntityTypeBasicComponent"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelDescription" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="New Component Model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components__Repository"
        upperBound="-1" eType="#//ProvidesComponentType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces__Repository"
        upperBound="-1" eType="#//Interface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedDelegationConnector" eSuperTypes="#//DelegationConnector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="innerAndOuterRoleNeedToHaveDifferentContextIDs InnerContainingComponentEqualOuterProvidingComponent"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerProvidedRole_ProvidedDelegationConnector"
        lowerBound="1" eType="#//ProvidedRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outerProvidedRole_ProvidedDelegationConnector"
        lowerBound="1" eType="#//ProvidedRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childComponentContext_ProvidedDelegationConnector"
        lowerBound="1" eType="#//ChildComponentContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementationComponentType" eSuperTypes="#//CompleteComponentType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="RequiredInterfacesHaveToConformToCompleteType providedInterfacesHaveToConformToCompleteType"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentCompleteComponentTypes"
        upperBound="-1" eType="#//CompleteComponentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompleteComponentType" eSuperTypes="#//ProvidesComponentType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="providedInterfacesHaveToConformToProvidedType2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentProvidesComponentTypes"
        upperBound="-1" eType="#//ProvidesComponentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" eSuperTypes="#//ImplementationComponentType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ProvideSameInterfaces RequireSameInterfaces"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedDelegationConnectors__CompositeComponent"
        upperBound="-1" eType="#//ProvidedDelegationConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredDelegationConnectors__CompositeComponent"
        upperBound="-1" eType="#//RequiredDelegationConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementationComponentType"
        eType="#//ImplementationComponentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childComponentContexts_CompositeComponent"
        upperBound="-1" eType="#//ChildComponentContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeAssemblyConnectors_CompositeComponent"
        upperBound="-1" eType="#//CompositeAssemblyConnector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeAssemblyConnector" eSuperTypes="PalladioCM.CorePackage.ecore#//Connectors/Connector PalladioCM.CorePackage.ecore#//Entity/Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiringChildComponentContext_CompositeAssemblyConnector"
        lowerBound="1" eType="#//ChildComponentContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providingChildComponentContext_CompositeAssemblyConnector"
        lowerBound="1" eType="#//ChildComponentContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedRole_CompositeAssemblyConnector"
        lowerBound="1" eType="#//ProvidedRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRole_CompositeAssemblyConnector"
        lowerBound="1" eType="#//RequiredRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicComponent" eSuperTypes="#//ImplementationComponentType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noSeffTypeUsedTwice ProvideSameInterfaces RequireSameInterfaces"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementationComponentType"
        eType="#//ImplementationComponentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceEffectSpecifications__BasicComponent"
        upperBound="-1" eType="ecore:EClass SEFFPackage.ecore#//ServiceEffectSpecification"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
