/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.pcm.allocation.validation;

import de.uka.ipd.sdq.pcm.allocation.AllocationContext;

import de.uka.ipd.sdq.pcm.resourceenvironment.ResourceEnvironment;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.pcm.allocation.Allocation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AllocationValidator {
	boolean validate();

	boolean validateAllocationContexts_Allocation(EList<AllocationContext> value);
	boolean validateTargetResourceEnvironment_Allocation(ResourceEnvironment value);
	boolean validateSystem_Allocation(de.uka.ipd.sdq.pcm.system.System value);
}
