<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="resultmodel"
    nsURI="http://sdq.ipd.uka.de/QueueingNetworkModel/ResultModel/1.0" nsPrefix="resultmodel">
  <eClassifiers xsi:type="ecore:EClass" name="QNMResultModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qnmodel" lowerBound="1"
        eType="ecore:EClass ../../de.uka.ipd.sdq.qnm/model/QueueingNetworkModel.ecore#//QNModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskResourceUsages" upperBound="-1"
        eType="#//TaskResourceUsage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceUsageTimes" upperBound="-1"
        eType="#//ResourceUsageTime" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskResourceUsage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queueLengthOneLess" lowerBound="1"
        eType="#//ManagedPMF"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queueLength" lowerBound="1"
        eType="#//ManagedPMF"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taskServiceTime" lowerBound="1"
        eType="#//ManagedPDF"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitingTimeOneLess" lowerBound="1"
        eType="#//ManagedPDF"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitingTime" lowerBound="1"
        eType="#//ManagedPDF"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.qnm/model/QueueingNetworkModel.ecore#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
        eType="ecore:EClass ../../de.uka.ipd.spq.spa.resourcemodel/model/ResourceModel.ecore#//Resource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ManagedPMF" instanceClassName="de.uka.ipd.sdq.probfunction.math.ManagedPMF">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ManagedPMF"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ManagedPDF" instanceClassName="de.uka.ipd.sdq.probfunction.math.ManagedPDF">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ManagedPDF"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceUsageTime">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceUsage" lowerBound="1"
        eType="ecore:EClass ../../de.uka.ipd.spq.spa.resourcemodel/model/ResourceModel.ecore#//AbstractResourceUsage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceTime" lowerBound="1"
        eType="#//ManagedPDF"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" lowerBound="1"
        eType="#//ManagedPDF"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceTimeBreakDowns"
        upperBound="-1" eType="#//ServiceTimeBreakDown" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceTimeBreakDown">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usageProbability" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usageTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedResource" lowerBound="1"
        eType="ecore:EClass ../../de.uka.ipd.spq.spa.resourcemodel/model/ResourceModel.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastUsageProbability" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastUsageTime" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
