package de.uka.ipd.sdq.dsexplore.analysis.lqn;

import org.apache.log4j.Logger;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.debug.core.ILaunch;
import org.eclipse.debug.core.ILaunchConfiguration;

import LqnCore.LqnModelType;

import de.uka.ipd.sdq.dsexplore.PCMInstance;
import de.uka.ipd.sdq.dsexplore.analysis.AnalysisFailedException;
import de.uka.ipd.sdq.dsexplore.analysis.IAnalysis;
import de.uka.ipd.sdq.dsexplore.analysis.IAnalysisResult;
import de.uka.ipd.sdq.dsexplore.helper.ConfigurationHelper;
import de.uka.ipd.sdq.pcmsolver.runconfig.PCMSolverLaunchConfigurationDelegate;
import de.uka.ipd.sdq.pcmsolver.transformations.pcm2lqn.LqnXmlHandler;
import de.uka.ipd.sdq.pcmsolver.transformations.pcm2lqn.Pcm2LqnStrategy;

/**
 * Starts a LQN simulation analysis for the design space exploration.
 * 
 * @author pmerkle
 *
 */
public class LQSimAnalysis implements IAnalysis {

	/** Logger for log4j. */
	private static Logger logger = 
		Logger.getLogger("de.uka.ipd.sdq.dsexplore");
	
	/**
	 * Store the launch parameters so that we do not have to pass them all the
	 * time.
	 */
	private String mode;
	/**
	 * Store the launch parameters so that we do not have to pass them all the
	 * time.
	 */
	private ILaunch launch;
	/**
	 * Store the launch parameters so that we do not have to pass them all the
	 * time.
	 */
	private IProgressMonitor monitor;
	/**
	 * Store the launch parameters so that we do not have to pass them all the
	 * time.
	 */
	private ILaunchConfiguration config;
	
	private int iteration = -1;
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public IAnalysisResult analyse(final PCMInstance pcmInstance)
			throws AnalysisFailedException, CoreException {
		
		iteration++;
		
		Pcm2LqnStrategy.FILENAME_RESULT_XML = System.getProperty("user.dir")
		+ System.getProperty("file.separator") + "pcm2lqn_result"+iteration+".xml";
				
		launchLQSim(pcmInstance);
		IAnalysisResult result = retrieveLQSimResults(pcmInstance);
		
		return result;
	}
	
	private IAnalysisResult retrieveLQSimResults(PCMInstance pcmInstance) throws AnalysisFailedException {
		// TODO: Move assignment of (currently hard-coded) file name to launch
		// configuration. Otherwise there seems to be no chance to retrieve the
		// file name without major changes to other classes. 
		// The change would also affect class Pcm2LqnStrategy.
		final String xmiFileName = System.getProperty("user.dir")
				+ System.getProperty("file.separator") + "pcm2lqn_result"+iteration+".xml";
		
		// Read XML output file generated by LQSim
		LqnModelType model =  LqnXmlHandler.loadModelFromXMI(xmiFileName);
		
		LQSimAnalysisResult result = new LQSimAnalysisResult(model, pcmInstance);
		
		return result;
	}
	
	/**
	 * Launches the LQN Simulation.
	 * 
	 * @param pcmInstance the instance of PCM
	 * @throws AnalysisFailedException 
	 * @throws CoreException 
	 */
	private void launchLQSim(final PCMInstance pcmInstance)
			throws AnalysisFailedException, CoreException {
		
		this.config = ConfigurationHelper.getInstance().updateConfig(config, pcmInstance);
		pcmInstance.saveUpdatesToFile();
		
		logger.debug("Starting analysis of "+pcmInstance.getName());
		
		PCMSolverLaunchConfigurationDelegate pcmSolver = new PCMSolverLaunchConfigurationDelegate();
		
		try {
			pcmSolver.launch(config, mode, launch, monitor);
			logger.debug("Finished PCMSolver analysis");
		} catch (CoreException e) {  
			String standardError = "PCMSolver launch failed for PCM instance \""+pcmInstance.getName()+"\"";
			logger.error(standardError);
			throw new AnalysisFailedException(standardError+": "+e.getMessage(), e);
		}
		
	}

	/**
	 * {@inheritDoc}
	 * @see de.uka.ipd.sdq.dsexplore.analysis.IAnalysis#initialise(org.eclipse.debug.core.ILaunchConfiguration, java.lang.String, org.eclipse.debug.core.ILaunch, org.eclipse.core.runtime.IProgressMonitor)
	 */
	public void initialise(ILaunchConfiguration configuration, String mode, ILaunch launch,IProgressMonitor monitor) {
		this.mode = mode;
		this.launch = launch;
		this.monitor = monitor;
		this.config = configuration;
	}
	
	@Override
	public IAnalysisResult retrieveLastResults(PCMInstance pcmInstance)
			throws CoreException, AnalysisFailedException {
		return retrieveLQSimResults(pcmInstance);
	}


}
