/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.pcm.core.composition.validation;

import de.uka.ipd.sdq.pcm.core.composition.AssemblyContext;
import de.uka.ipd.sdq.pcm.core.composition.ComposedStructure;

import de.uka.ipd.sdq.pcm.repository.ProvidedRole;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.pcm.core.composition.ProvidedDelegationConnector}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProvidedDelegationConnectorValidator {
	boolean validate();

	boolean validateInnerProvidedRole_ProvidedDelegationConnector(ProvidedRole value);
	boolean validateOuterProvidedRole_ProvidedDelegationConnector(ProvidedRole value);
	boolean validateChildComponentContext_ProvidedDelegationConnector(AssemblyContext value);
	boolean validateParentStructure_ProvidedDelegationConnector(ComposedStructure value);
}
