<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="StoExAlternatives"
    nsURI="http:///StoExAlternatives.ecore" nsPrefix="StoExAlternatives">
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionProxy" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.stoex/model/stoex.ecore#//Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="StoEx variation point"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternatives" ordered="false"
        upperBound="-1" eType="#//StoExPart" eOpposite="#//StoExPart/expressionProxy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/de.uka.ipd.sdq.stoex/model/stoex.ecore#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StoExPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subExpression" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/de.uka.ipd.sdq.stoex/model/stoex.ecore#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressionProxy" ordered="false"
        lowerBound="1" eType="#//ExpressionProxy" eOpposite="#//ExpressionProxy/alternatives"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProxyRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressionProxy" ordered="false"
        upperBound="-1" eType="#//ExpressionProxy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stoExPart" ordered="false"
        upperBound="-1" eType="#//StoExPart" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
