<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sensitivity"
    nsURI="http://sdq.ipd.uka.de/Sensitivity/1.0" nsPrefix="sensitivity">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="&lt;p>&#xD;&#xA;    This package allows for the specification of a sensitivity analysis for PCM models.&#xD;&#xA;&lt;/p>"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SensitivityConfiguration" eSuperTypes="../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Root&amp;nbsp;class&amp;nbsp;of&amp;nbsp;a&amp;nbsp;sensitivity&amp;nbsp;analysis&amp;nbsp;configuration.&amp;nbsp;The&amp;nbsp;configuration&amp;nbsp;specifies&amp;nbsp;one&amp;nbsp;or&amp;nbsp;multiple&amp;nbsp;parameter&amp;nbsp;variations&amp;nbsp;in&amp;nbsp;a&lt;br />&#xD;&#xA;PCM&amp;nbsp;model.&amp;nbsp;Together,&amp;nbsp;the&amp;nbsp;parameter&amp;nbsp;variations&amp;nbsp;constitute&amp;nbsp;a&amp;nbsp;variation&amp;nbsp;of&amp;nbsp;the&amp;nbsp;PCM&amp;nbsp;model,&amp;nbsp;i.e.&amp;nbsp;a&amp;nbsp;sequence&amp;nbsp;of&amp;nbsp;related&amp;nbsp;PCM&amp;nbsp;models.&lt;br />&#xD;&#xA;This&amp;nbsp;information&amp;nbsp;can&amp;nbsp;be&amp;nbsp;used&amp;nbsp;to&amp;nbsp;perform&amp;nbsp;a&amp;nbsp;sensitivity&amp;nbsp;analysis,&amp;nbsp;i.e.&amp;nbsp;a&amp;nbsp;repeated&amp;nbsp;analysis&amp;nbsp;for&amp;nbsp;each&amp;nbsp;of&amp;nbsp;the&amp;nbsp;defined&amp;nbsp;PCM&lt;br />&#xD;&#xA;models."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensitivityParameters__SensitivityConfiguration"
        ordered="false" lowerBound="1" eType="#//SensitivityParameter" containment="true"
        eOpposite="#//SensitivityParameter/sensitivityConfiguration__SensitivityParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensitivityResultSpecifications__SensitivityConfiguration"
        ordered="false" upperBound="-1" eType="#//SensitivityResultSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensitivityParameter" abstract="true"
      eSuperTypes="../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Specifies&amp;nbsp;a&amp;nbsp;variation&amp;nbsp;of&amp;nbsp;a&amp;nbsp;certain&amp;nbsp;parameter&amp;nbsp;in&amp;nbsp;a&amp;nbsp;given&amp;nbsp;PCM&amp;nbsp;model.&amp;nbsp;Thereby,&amp;nbsp;a&amp;nbsp;&quot;parameter&quot;&amp;nbsp;may&amp;nbsp;be&amp;nbsp;a&amp;nbsp;single&amp;nbsp;value&amp;nbsp;(such&amp;nbsp;as&#xD;&#xA;a&#xD;&#xA;resource&amp;nbsp;demand),&amp;nbsp;a&amp;nbsp;group&amp;nbsp;of&amp;nbsp;values&amp;nbsp;(such&amp;nbsp;as&amp;nbsp;all&amp;nbsp;software&amp;nbsp;failure&amp;nbsp;probabilities&amp;nbsp;in&amp;nbsp;a&amp;nbsp;given&amp;nbsp;RDSEFF),&#xD;&#xA;or a combination of other parameters.&amp;nbsp;If&amp;nbsp;the&amp;nbsp;parameter&amp;nbsp;is&amp;nbsp;a&#xD;&#xA;single&amp;nbsp;value,&amp;nbsp;it&amp;nbsp;may&amp;nbsp;be&amp;nbsp;of&amp;nbsp;different&amp;nbsp;types,&amp;nbsp;such&amp;nbsp;as&amp;nbsp;DOUBLE&amp;nbsp;or&amp;nbsp;STRING."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentParameter__SensitivityParameter"
        ordered="false" eType="#//CombinedSensitivityParameter" eOpposite="#//CombinedSensitivityParameter/childParameters__CombinedSensitivityParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensitivityConfiguration__SensitivityParameter"
        ordered="false" eType="#//SensitivityConfiguration" eOpposite="#//SensitivityConfiguration/sensitivityParameters__SensitivityConfiguration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedSensitivityParameter" eSuperTypes="#//SensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A&amp;nbsp;combined&amp;nbsp;sensitivity&amp;nbsp;parameter&amp;nbsp;consists&amp;nbsp;of&amp;nbsp;a&amp;nbsp;set&amp;nbsp;of&amp;nbsp;child parameters. The&#xD;&#xA;child parameters define individual variations that are&amp;nbsp;aggregated into an overall variation. The type&#xD;&#xA;of&amp;nbsp;variation is determined through the isCombinatory attribute."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCombinatory" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;p>&#xD;&#xA;    This attribute determines how the child parameters are aggregated into a combined parameter. For example, let S1 and S2&#xD;&#xA;    be two child parameters, with S1 defining a sequence of changing model values {p1, p2} and S2 defining another sequence&#xD;&#xA;    {q1, q2, q3}. The two&amp;nbsp;child parameters&amp;nbsp;are combined as follows:&#xD;&#xA;&lt;/p>&#xD;&#xA;&lt;p>&#xD;&#xA;    If isCombinatory == true, the product of both sequences is used: {(p1q1), (p1q2), (p1q3), (p2q1), (p2q2), (p2q3)}&#xD;&#xA;&lt;/p>&#xD;&#xA;&lt;p>&#xD;&#xA;    If isCombinatory == false, both sequences proceed in parallel. The shorter sequence&amp;nbsp;keeps&amp;nbsp;its last value&#xD;&#xA;    until the longer sequence is finished: {(p1q1), (p2q2), (p2q3)}&#xD;&#xA;&lt;/p>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childParameters__CombinedSensitivityParameter"
        ordered="false" lowerBound="1" upperBound="-1" eType="#//SensitivityParameter"
        containment="true" eOpposite="#//SensitivityParameter/parentParameter__SensitivityParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensitivityResultSpecification" abstract="true"
      eSuperTypes="../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//core/entity/Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for result specifications, i.e. specifications of the Markov transformation results of interest."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleSensitivityParameter" abstract="true"
      eSuperTypes="#//SensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for all single (i.e. not combined) sensitivity parameters."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensitivityParameterVariation__SingleSensitivityParameter"
        ordered="false" lowerBound="1" eType="#//SensitivityParameterVariation" containment="true"
        eOpposite="#//SensitivityParameterVariation/singleSensitivityParameter__SensitivityParameterVariation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensitivityParameterVariation" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Specifies how a given sensitivity parameter shall be varied. From this specification, a sequence of parameter values can be&#xD;&#xA;determined that constitutes the variation."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleSensitivityParameter__SensitivityParameterVariation"
        ordered="false" lowerBound="1" eType="#//SingleSensitivityParameter" eOpposite="#//SingleSensitivityParameter/sensitivityParameterVariation__SingleSensitivityParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentReliabilityParameter" eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This parameter refers to the set of all software failure probabilities specified in the context of the given&#xD;&#xA;BasicComponent. All software failure probabilities are altered together according to the same sequence of values."/>
    </eAnnotations>
    <eOperations name="ComponentReliabilityParameterMustHaveDoubleVariation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(DoubleParameterVariation)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicComponent__ComponentReliabilityParameter"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//repository/BasicComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleParameterVariation" abstract="true"
      eSuperTypes="#//SensitivityParameterVariation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>&#xD;&#xA;    Specifies&amp;nbsp;a variation&amp;nbsp;of&amp;nbsp;a&amp;nbsp;sensitivity parameter of type DOUBLE.&#xD;&#xA;&lt;/p>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringParameterSequence" eSuperTypes="#//SensitivityParameterVariation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>&#xD;&#xA;    Specifies&amp;nbsp;a variation&amp;nbsp;of&amp;nbsp;a&amp;nbsp;sensitivity parameter of type STRING (e.g. for stochastic expressions).&#xD;&#xA;    The specification is given as a sequence of strings.&#xD;&#xA;&lt;/p>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringValues" ordered="false"
        unique="false" lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The&amp;nbsp;list&amp;nbsp;of&amp;nbsp;STRING&amp;nbsp;values."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleParameterRange" eSuperTypes="#//DoubleParameterVariation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Specifies&amp;nbsp;a value range (i.e. an interval) with a given step size or step count, to define&amp;nbsp;a&#xD;&#xA;variation&amp;nbsp;of&amp;nbsp;a&amp;nbsp;sensitivity parameter of type DOUBLE."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="considerStepSize" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Decides&amp;nbsp;if&amp;nbsp;the&amp;nbsp;step&amp;nbsp;width&amp;nbsp;is&amp;nbsp;used&amp;nbsp;to&amp;nbsp;determine&amp;nbsp;the&amp;nbsp;value&amp;nbsp;sequence&amp;nbsp;(considerStepSize&amp;nbsp;==&amp;nbsp;true)&amp;nbsp;or&amp;nbsp;the&amp;nbsp;step&amp;nbsp;count&lt;br />&#xD;&#xA;(considerStepSize&amp;nbsp;==&amp;nbsp;false)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstValue" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastValue" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepSize" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepCount" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleParameterSequence" eSuperTypes="#//DoubleParameterVariation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Specifies&amp;nbsp;a sequence of values, to define&amp;nbsp;a variation&amp;nbsp;of&amp;nbsp;a&amp;nbsp;sensitivity parameter of type DOUBLE."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubleValues" unique="false"
        lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The&amp;nbsp;list&amp;nbsp;of&amp;nbsp;DOUBLE&amp;nbsp;values."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleParameterFunction" abstract="true"
      eSuperTypes="#//DoubleParameterVariation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Specifies&amp;nbsp;a parameterized function (such as a bath tub curve&amp;nbsp;that may represent&amp;nbsp;hardware MTTF progression&#xD;&#xA;over time). No concrete examples defined so far."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalActionReliabilityParameter"
      eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This&amp;nbsp;parameter&amp;nbsp;refers&amp;nbsp;to&amp;nbsp;a&#xD;&#xA;software&amp;nbsp;failure&amp;nbsp;probability&amp;nbsp;specified&amp;nbsp;in&amp;nbsp;the&amp;nbsp;context&amp;nbsp;of&amp;nbsp;the&amp;nbsp;given&#xD;&#xA;InternalAction for the given SoftwareInducedFailureType."/>
    </eAnnotations>
    <eOperations name="InternalActionReliabilityParameterMustHaveDoubleVariation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(DoubleParameterVariation)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareInducedFailureType__InternalActionReliabilityParameter"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//reliability/SoftwareInducedFailureType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalAction__InternalActionReliabilityParameter"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/InternalAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProbabilisticBranchParameter" eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This&amp;nbsp;parameter&amp;nbsp;refers&amp;nbsp;to&amp;nbsp;a&amp;nbsp;branch&#xD;&#xA;transition&amp;nbsp;probability&amp;nbsp;specified&amp;nbsp;in&amp;nbsp;the&amp;nbsp;context&amp;nbsp;of&amp;nbsp;the&amp;nbsp;given&#xD;&#xA;ProbabilisticBranchTransition."/>
    </eAnnotations>
    <eOperations name="ProbabilisticBranchParameterMustHaveDoubleVariation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(DoubleParameterVariation)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="probabilisticBranchTransition__ProbabilisticBranchParameter"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//seff/ProbabilisticBranchTransition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HardwareMTTFParameter" eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This parameter refers to the set of all processing resource MTTF values specified in the given PCM instance. All MTTFs are&#xD;&#xA;altered together according to the same sequence of values."/>
    </eAnnotations>
    <eOperations name="HardwareMTTFParameterMustHaveDoubleVariation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(DoubleParameterVariation)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HardwareMTTRParameter" eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This parameter refers to the set of all processing resource MTTR values specified in the given PCM instance. All MTTRs are&#xD;&#xA;altered together according to the same sequence of values."/>
    </eAnnotations>
    <eOperations name="HardwareMTTRParameterMustHaveDoubleVariation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(DoubleParameterVariation)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceMTTFParameter" eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This parameter refers to an MTTF value&amp;nbsp;of a given ProcessingResourceSpecification."/>
    </eAnnotations>
    <eOperations name="ResourceMTTFParameterMustHaveDoubleVariation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(DoubleParameterVariation)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingResourceType__ResourceMTTFParameter"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourcetype/ProcessingResourceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceContainer__ResourceMTTFParameter"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceMTTRParameter" eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This parameter refers to an MTTR value of a given ProcessingResourceSpecification."/>
    </eAnnotations>
    <eOperations name="ResourceMTTRParameterMustHaveDoubleVariation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(DoubleParameterVariation)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceContainer__ResourceMTTRParameter"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingResourceType__ResourceMTTRParameter"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourcetype/ProcessingResourceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkReliabilityParameter" eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This parameter refers to the set of all network failure probabilities specified in the given PCM instance.&#xD;&#xA;All&amp;nbsp;probabilities are altered together according to the same sequence of values."/>
    </eAnnotations>
    <eOperations name="NetworkReliabilityParameterMustHaveDoubleVariation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(DoubleParameterVariation)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationLinkReliabilityParameter"
      eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This parameter refers to a network failure probability specified in the context of the given&#xD;&#xA;CommunicationLinkResourceSpecification."/>
    </eAnnotations>
    <eOperations name="CommunicationLinkParameterMustHaveDoubleVariation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(DoubleParameterVariation)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communicationLinkResourceSpecification__CommunicationLinkReliabilityParameter"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourceenvironment/CommunicationLinkResourceSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareReliabilityParameter" eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This parameter refers to the set of all software failure probabilities specified for the given PCM instance. All&#xD;&#xA;probabilities are altered together according to the same sequence of values."/>
    </eAnnotations>
    <eOperations name="SoftwareReliabilityParameterMustHaveDoubleVariation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(DoubleParameterVariation)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableUsageParameter" eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This&amp;nbsp;parameter&amp;nbsp;refers&amp;nbsp;to&amp;nbsp;a&amp;nbsp;stochastic&amp;nbsp;specification&amp;nbsp;of&amp;nbsp;a variable usage."/>
    </eAnnotations>
    <eOperations name="SystemCallParameterMustHaveStringSequence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(StringParameterSequence)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VariableName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryLevelSystemCall__VariableUsageParameter"
        ordered="false" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//usagemodel/EntryLevelSystemCall"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableCharacterisationType__VariableUsageParameter"
        ordered="false" lowerBound="1" eType="ecore:EEnum ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//parameter/VariableCharacterisationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableUsageType__VariableUsageParameter"
        ordered="false" lowerBound="1" eType="#//VariableUsageType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicComponent__VariableUsageParameter"
        ordered="false" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//repository/BasicComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VariableUsageType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Specifies a type of variable usage in a PCM Instance"/>
    </eAnnotations>
    <eLiterals name="SYSTEM_CALL_INPUT"/>
    <eLiterals name="COMPONENT_CONFIGURATION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsageBranchParameter" eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This&amp;nbsp;parameter&amp;nbsp;refers&amp;nbsp;to&amp;nbsp;a&amp;nbsp;branch&amp;nbsp;transition&amp;nbsp;probability&amp;nbsp;specified&amp;nbsp;in&amp;nbsp;the&amp;nbsp;context&amp;nbsp;of&amp;nbsp;the&amp;nbsp;given&amp;nbsp;user&#xD;&#xA;Branch."/>
    </eAnnotations>
    <eOperations name="UsageBranchParameterMustHaveDoubleVariation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(DoubleParameterVariation)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branch__UsageBranchParameter"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//usagemodel/Branch"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioBehaviour__UsageBranchParameter"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//usagemodel/ScenarioBehaviour"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleOffsetSequence" eSuperTypes="#//DoubleParameterVariation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Specifies a sequence of values, to define a variation of a sensitivity parameter of type DOUBLE. The given values are used&#xD;&#xA;as offsets to adjust the original model value."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offsetValues" ordered="false"
        unique="false" lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubleOffsetType__DoubleOffsetSequence"
        ordered="false" lowerBound="1" eType="#//DoubleOffsetType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DoubleOffsetType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>&#xD;&#xA;    Specifies the type of offset represented by a double value (val_off) that is connected to an original value (val_orig)&#xD;&#xA;    to achieve a new result value (val_res):&#xD;&#xA;&lt;/p>&#xD;&#xA;&lt;p>&#xD;&#xA;    ADD: val_res = val_orig + val_off&#xD;&#xA;&lt;/p>&#xD;&#xA;&lt;p>&#xD;&#xA;    SUBTRACT: val_res = val_orig - val_off&#xD;&#xA;&lt;/p>&#xD;&#xA;&lt;p>&#xD;&#xA;    MULTIPLY: val_res = val_orig * val_off&#xD;&#xA;&lt;/p>&#xD;&#xA;&lt;p>&#xD;&#xA;    DIVIDE: val_res = val_orig / val_off&#xD;&#xA;&lt;/p>"/>
    </eAnnotations>
    <eLiterals name="ADD"/>
    <eLiterals name="SUBTRACT" value="1"/>
    <eLiterals name="MULTIPLY" value="2"/>
    <eLiterals name="DIVIDE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareFailureTypesParameter" eSuperTypes="#//SingleSensitivityParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This parameter refers to all software failure probabilities specified for the given SoftwareInducedFailureType."/>
    </eAnnotations>
    <eOperations name="SoftwareFailureTypeReliabilityParameterMustHaveDoubleVariation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.sensitivityParameterVariation__SingleSensitivityParameter.oclIsTypeOf(DoubleParameterVariation)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareInducedFailureTypes__SoftwareFailureTypeReliabilityParameter"
        ordered="false" lowerBound="1" upperBound="-1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//reliability/SoftwareInducedFailureType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FailureTypeResultSpecification" eSuperTypes="#//SensitivityResultSpecification">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Describes the overall failure potential&amp;nbsp;associated with&amp;nbsp;the specified set of failure types."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failureTypes__FailureTypeResultSpecification"
        ordered="false" lowerBound="1" upperBound="-1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//reliability/FailureType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FailureDimensionResultSpecification"
      eSuperTypes="#//SensitivityResultSpecification">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Describes the overall failure potential associated with one dimension of failure types (software-induced, hardware-induced,&#xD;&#xA;network-induced)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureDimension__FailureDimensionResultSpecification"
        ordered="false" lowerBound="1" eType="#//FailureDimension"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FailureDimension">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Describes a dimension of failure types (software-induced, hardware-induced or network-induced)."/>
    </eAnnotations>
    <eLiterals name="SOFTWARE"/>
    <eLiterals name="HARDWARE" value="1"/>
    <eLiterals name="NETWORK" value="2"/>
  </eClassifiers>
</ecore:EPackage>
