<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="AssemblyPackage"
    nsURI="http:///PalladioCM/AssemblyPackage.ecore" nsPrefix="PalladioCM.AssemblyPackage">
  <eClassifiers xsi:type="ecore:EClass" name="SystemAssemblyConnector" eSuperTypes="PalladioCM.CorePackage.ecore#//Connectors/Connector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="contextIDsOfProvidesRoleNotEqualRequiresRole"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providingContext_SystemAssemblyConnector"
        lowerBound="1" eType="#//AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiringContext_SystemAssemblyConnector"
        lowerBound="1" eType="#//AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedRole_SystemAssemblyConnector"
        lowerBound="1" eType="ecore:EClass RepositoryPackage.ecore#//ProvidedRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRole_SystemAssemblyConnector"
        lowerBound="1" eType="ecore:EClass RepositoryPackage.ecore#//RequiredRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext" eSuperTypes="PalladioCM.CorePackage.ecore#//Entity/Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulatedComponent__AssemblyContext"
        lowerBound="1" eType="ecore:EClass RepositoryPackage.ecore#//ProvidesComponentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assembly" eSuperTypes="PalladioCM.CorePackage.ecore#//Entity/Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblycontexts_Assembly"
        upperBound="-1" eType="#//AssemblyContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyConnectors_Assembly"
        upperBound="-1" eType="#//SystemAssemblyConnector" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
