<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ByBench"
    nsURI="http://sdq.ipd.uka.de/ByBench/1.0" nsPrefix="ByBench">
  <eClassifiers xsi:type="ecore:EClass" name="Scenario" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioprecondition" ordered="false"
        lowerBound="1" eType="#//ScenarioPrecondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measurementstart" ordered="false"
        lowerBound="1" eType="#//MeasurementStart" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenariocore" ordered="false"
        lowerBound="1" eType="#//ScenarioCore" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measurementend" ordered="false"
        lowerBound="1" eType="#//MeasurementEnd" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenariopostcondition"
        ordered="false" lowerBound="1" eType="#//ScenarioPostcondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedcardinality" ordered="false"
        upperBound="-1" eType="#//NamedCardinality" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="benchmarkedInstruction"
        ordered="false" lowerBound="1" eType="#//AtomicInstruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioPrecondition" eSuperTypes="#//InstructionSequence ../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstructionSequence" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceelement" ordered="false"
        upperBound="-1" eType="#//SequenceElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceElement" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor" ordered="false"
        eType="#//SequenceElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasurementStart" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioCore" eSuperTypes="#//InstructionSequence ../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="MeasurementEnd" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioPostcondition" eSuperTypes="#//InstructionSequence ../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedCardinality" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinalityValue" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinalityName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructionchaining" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//InstructionChaining" eOpposite="#//InstructionChaining/namedcardinality"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructionlooping" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//InstructionLooping" eOpposite="#//InstructionLooping/namedcardinality"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstructionChaining" eSuperTypes="#//SequenceElement ../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructionsequence" ordered="false"
        lowerBound="1" eType="#//InstructionSequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedcardinality" ordered="false"
        lowerBound="1" eType="#//NamedCardinality" eOpposite="#//NamedCardinality/instructionchaining"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstructionLooping" eSuperTypes="#//SequenceElement ../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructionsequence" ordered="false"
        upperBound="-1" eType="#//InstructionSequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedcardinality" ordered="false"
        lowerBound="1" eType="#//NamedCardinality" eOpposite="#//NamedCardinality/instructionlooping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicInstruction" eSuperTypes="#//SequenceElement ../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eOperations name="ensureValidOpcode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.opcode > 0 and  self.opcode &lt; 256&#xD;&#xA;"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ParameterValue" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ParameterConversion" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opcode" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
