/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.pcm.parameter.validation;

import de.uka.ipd.sdq.pcm.parameter.VariableCharacterisationType;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.pcm.parameter.CharacterisedVariable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CharacterisedVariableValidator {
	boolean validate();

	boolean validateCharacterisationType(VariableCharacterisationType value);
}
