<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FSMModel"
    nsURI="http:///FSMModel.ecore" nsPrefix="FSMModel">
  <eClassifiers xsi:type="ecore:EClass" name="FiniteStateMachine">
    <eAnnotations source="uml2.alias">
      <details key="FSM"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputsymbol" upperBound="-1"
        eType="#//InputSymbol" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startState" lowerBound="1"
        eType="#//State" eOpposite="#//State/transitionsStart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endState" lowerBound="1"
        eType="#//State" eOpposite="#//State/transitionsEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputSymbol" lowerBound="1"
        eType="#//InputSymbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionsStart" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/startState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionsEnd" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/endState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStartState" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEndState" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputSymbol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
</ecore:EPackage>
