/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.pcm.allocation.validation;

import de.uka.ipd.sdq.pcm.core.composition.AssemblyContext;

import de.uka.ipd.sdq.pcm.resourceenvironment.ResourceContainer;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.pcm.allocation.AllocationContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AllocationContextValidator {
	boolean validate();

	boolean validateResourceContainer_AllocationContext(ResourceContainer value);
	boolean validateAssemblyContext_AllocationContext(AssemblyContext value);
}
