<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qnm"
    nsURI="http://sdq.ipd.uka.de/QueueingNetworkModel/1.0" nsPrefix="qnm">
  <eClassifiers xsi:type="ecore:EClass" name="QNModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers" unique="false"
        upperBound="-1" eType="#//Customer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servers" upperBound="-1"
        eType="#//Server" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="INFINITE" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eOperations name="getAllDemands" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="demand" unique="false"
        lowerBound="1" eType="#//Demand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Demand" abstract="true">
    <eOperations name="getUsedResources" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Server" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceServer" eSuperTypes="#//Server"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalServer" eSuperTypes="#//Server"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalDemand" abstract="true" eSuperTypes="#//Demand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicalserver" lowerBound="1"
        eType="#//LogicalServer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="demands" upperBound="-1"
        eType="#//Demand" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceDemand" eSuperTypes="#//Demand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceServer" lowerBound="1"
        eType="#//DeviceServer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceTime" unique="false"
        lowerBound="1" eType="#//ManagedPDF"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ManagedPDF" instanceClassName="de.uka.ipd.sdq.probfunction.math.ManagedPDF">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ManagedPDF"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequentialDemand" eSuperTypes="#//LogicalDemand"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeDemand" eSuperTypes="#//LogicalDemand"/>
  <eClassifiers xsi:type="ecore:EClass" name="IterativeDemand" eSuperTypes="#//LogicalDemand"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelDemand" eSuperTypes="#//LogicalDemand"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ManagedPMF" instanceClassName="de.uka.ipd.sdq.probfunction.math.ManagedPMF">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ManagedPMF"/>
    </eAnnotations>
  </eClassifiers>
  <eSubpackages name="qnResult" nsURI="http://sdq.ipd.uka.de/QueueingNetworkModel/QNResult/1.0"
      nsPrefix="qnm.qnResult">
    <eClassifiers xsi:type="ecore:EClass" name="DemandServerUsage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="demand" lowerBound="1"
          eType="#//qnResult/DemandResult" eOpposite="#//qnResult/DemandResult/serverUsages"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="server" lowerBound="1"
          eType="#//qnResult/ServerResult" eOpposite="#//qnResult/ServerResult/usageDemands"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usageProbability" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="meanUsageTime" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DemandResult">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" lowerBound="1"
          eType="#//ManagedPDF"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="serverUsages" upperBound="-1"
          eType="#//qnResult/DemandServerUsage" eOpposite="#//qnResult/DemandServerUsage/demand"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="demand" lowerBound="1"
          eType="#//Demand"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceTime" lowerBound="1"
          eType="#//ManagedPDF"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServerResult">
      <eOperations name="getUsageByCustomer" eType="#//qnResult/CustomerServerUsage">
        <eParameters name="customer" eType="#//Customer"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usingCustomers" upperBound="-1"
          eType="#//qnResult/CustomerServerUsage" eOpposite="#//qnResult/CustomerServerUsage/serverResult"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="server" lowerBound="1"
          eType="#//Server"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usageDemands" upperBound="-1"
          eType="#//qnResult/DemandServerUsage" eOpposite="#//qnResult/DemandServerUsage/server"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomerServerUsage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="customerResult" lowerBound="1"
          eType="#//qnResult/CustomerResult" eOpposite="#//qnResult/CustomerResult/serverUsage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="serverResult" lowerBound="1"
          eType="#//qnResult/ServerResult" eOpposite="#//qnResult/ServerResult/usingCustomers"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="causedWaitingTime" lowerBound="1"
          eType="#//ManagedPDF"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="causedWaitingTimeOneLess"
          lowerBound="1" eType="#//ManagedPDF"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="queueLength" lowerBound="1"
          eType="#//ManagedPMF"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="queueLengthOneLess" lowerBound="1"
          eType="#//ManagedPMF"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="demandsToServer" upperBound="-1"
          eType="#//qnResult/DemandResult"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="customerServiceTime"
          lowerBound="1" eType="#//ManagedPDF"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomerResult">
      <eOperations name="getServerUsage" eType="#//qnResult/CustomerServerUsage">
        <eParameters name="server" eType="#//Server"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="customer" lowerBound="1"
          eType="#//Customer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="serverUsage" upperBound="-1"
          eType="#//qnResult/CustomerServerUsage" eOpposite="#//qnResult/CustomerServerUsage/customerResult"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QNResultModel">
      <eOperations name="getResultForServer" eType="#//qnResult/ServerResult">
        <eParameters name="server" eType="#//Server"/>
      </eOperations>
      <eOperations name="getResultForCustomer" eType="#//qnResult/CustomerResult">
        <eParameters name="customer" eType="#//Customer"/>
      </eOperations>
      <eOperations name="getResultForDemand" eType="#//qnResult/DemandResult">
        <eParameters name="demand" eType="#//Demand"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="customerServerUsage"
          upperBound="-1" eType="#//qnResult/CustomerServerUsage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qnModel" lowerBound="1"
          eType="#//QNModel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="customerResults" upperBound="-1"
          eType="#//qnResult/CustomerResult" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="serverResults" upperBound="-1"
          eType="#//qnResult/ServerResult" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="demandResults" upperBound="-1"
          eType="#//qnResult/DemandResult" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="demandServerUsages" upperBound="-1"
          eType="#//qnResult/DemandServerUsage" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
