/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.pcm.core.composition.validation;

import de.uka.ipd.sdq.pcm.core.composition.AssemblyConnector;
import de.uka.ipd.sdq.pcm.core.composition.AssemblyContext;
import de.uka.ipd.sdq.pcm.core.composition.ProvidedDelegationConnector;
import de.uka.ipd.sdq.pcm.core.composition.RequiredDelegationConnector;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.pcm.core.composition.ComposedStructure}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComposedStructureValidator {
	boolean validate();

	boolean validateChildComponentContexts_ComposedStructure(EList<AssemblyContext> value);
	boolean validateProvidedDelegationConnectors_ComposedStructure(EList<ProvidedDelegationConnector> value);
	boolean validateRequiredDelegationConnectors_ComposedStructure(EList<RequiredDelegationConnector> value);
	boolean validateCompositeAssemblyConnectors_ComposedStructure(EList<AssemblyConnector> value);
}
