/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.context.actual_allocation.validation;

import de.uka.ipd.sdq.pcm.seff.ParametricResourceDemand;

import de.uka.ipd.sdq.stoex.RandomVariable;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.context.actual_allocation.ActualResourceDemand}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActualResourceDemandValidator {
	boolean validate();

	boolean validateParametricResourceDemand_ActualResourceDemand(ParametricResourceDemand value);
	boolean validateRandomVariable_ActualResourceDemand(RandomVariable value);
}
