/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.pcm.resourceenvironment.validation;

import de.uka.ipd.sdq.pcm.resourcetype.ProcessingResourceType;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.pcm.resourceenvironment.ProcessingResourceSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProcessingResourceSpecificationValidator {
	boolean validate();

	boolean validateActiveResourceType_ActiveResourceSpecification(ProcessingResourceType value);
	boolean validateProcessingRate(double value);
	boolean validateUnits(String value);
}
