/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.pcm.seff.validation;

import de.uka.ipd.sdq.pcm.resourcetype.ProcessingResourceType;

import de.uka.ipd.sdq.pcm.seff.AbstractResourceDemandingAction;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.pcm.seff.ParametricResourceDemand}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParametricResourceDemandValidator {
	boolean validate();

	boolean validateUnit(String value);
	boolean validateRequiredResource_ParametricResourceDemand(ProcessingResourceType value);
	boolean validateAction_ParametricResourceDemand(AbstractResourceDemandingAction value);
}
