<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="featureconfig"
    nsURI="http://sdq.ipd.uka.de/FeatureConfig" nsPrefix="featureconfig">
  <eClassifiers xsi:type="ecore:EClass" name="ConfigNode">
    <eOperations name="ConfigCardinalityInvalid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="let childSelectedCount : Integer = self.children->select(c|c.configState = ConfigState::USER_SELECTED or c.configState = ConfigState::MASCHINE_SELECTED)->size() &#xD;&#xA;in &#xD;&#xA;&#x9; if self.origin.oclIsTypeOf(featuremodel::FeatureGroup) then&#xD;&#xA;&#x9; &#x9;childSelectedCount >= self.origin.min and (childSelectedCount &lt;= self.origin.max or self.origin.max = -1)&#xD;&#xA;&#x9; else&#xD;&#xA;&#x9; &#x9;self.origin.min  >= 1 implies (self.configState = ConfigState::USER_SELECTED or self.configState = ConfigState::MASCHINE_SELECTED)&#xD;&#xA;&#x9; endif"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" ordered="false"
        lowerBound="1" eType="ecore:EClass FeatureModel.ecore#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configState" ordered="false"
        lowerBound="1" eType="#//ConfigState" defaultValueLiteral="DEFAULT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConfigState">
    <eLiterals name="SELECTED"/>
    <eLiterals name="ELIMINATED" value="1"/>
    <eLiterals name="DEFAULT" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="use value from deaultConfig&#xD;&#xA;aka NULL, not set, do not override"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureConfig">
    <eOperations name="RootIsFeatureModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.origin.oclIsTypeOf(featuremodel::FeatureDiagram)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedObject" ordered="false"
        eType="ecore:EClass Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="confignode" ordered="false"
        upperBound="-1" eType="#//ConfigNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultConfig" ordered="false"
        lowerBound="1" eType="#//FeatureConfig" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configOverrides" ordered="false"
        lowerBound="1" eType="#//FeatureConfig" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
