/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.fzi.se.controlflowdescription.jjnpaths.provider;

import de.fzi.se.controlflowdescription.jjnpaths.util.JJnPathsAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class JJnPathsItemProviderAdapterFactory extends JJnPathsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public JJnPathsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.fzi.se.controlflowdescription.jjnpaths.JJnPathTestSuite} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JJnPathTestSuiteItemProvider jJnPathTestSuiteItemProvider;

	/**
	 * This creates an adapter for a {@link de.fzi.se.controlflowdescription.jjnpaths.JJnPathTestSuite}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJJnPathTestSuiteAdapter() {
		if (jJnPathTestSuiteItemProvider == null) {
			jJnPathTestSuiteItemProvider = new JJnPathTestSuiteItemProvider(this);
		}

		return jJnPathTestSuiteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.fzi.se.controlflowdescription.jjnpaths.JJnPath} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JJnPathItemProvider jJnPathItemProvider;

	/**
	 * This creates an adapter for a {@link de.fzi.se.controlflowdescription.jjnpaths.JJnPath}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJJnPathAdapter() {
		if (jJnPathItemProvider == null) {
			jJnPathItemProvider = new JJnPathItemProvider(this);
		}

		return jJnPathItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.fzi.se.controlflowdescription.jjnpaths.JJPath} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JJPathItemProvider jjPathItemProvider;

	/**
	 * This creates an adapter for a {@link de.fzi.se.controlflowdescription.jjnpaths.JJPath}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJJPathAdapter() {
		if (jjPathItemProvider == null) {
			jjPathItemProvider = new JJPathItemProvider(this);
		}

		return jjPathItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.fzi.se.controlflowdescription.jjnpaths.JJnPathTestCase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JJnPathTestCaseItemProvider jJnPathTestCaseItemProvider;

	/**
	 * This creates an adapter for a {@link de.fzi.se.controlflowdescription.jjnpaths.JJnPathTestCase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJJnPathTestCaseAdapter() {
		if (jJnPathTestCaseItemProvider == null) {
			jJnPathTestCaseItemProvider = new JJnPathTestCaseItemProvider(this);
		}

		return jJnPathTestCaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.fzi.se.controlflowdescription.jjnpaths.JJnPathsCreationParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JJnPathsCreationParameterItemProvider jJnPathsCreationParameterItemProvider;

	/**
	 * This creates an adapter for a {@link de.fzi.se.controlflowdescription.jjnpaths.JJnPathsCreationParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJJnPathsCreationParameterAdapter() {
		if (jJnPathsCreationParameterItemProvider == null) {
			jJnPathsCreationParameterItemProvider = new JJnPathsCreationParameterItemProvider(this);
		}

		return jJnPathsCreationParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.fzi.se.controlflowdescription.jjnpaths.JJnPathSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JJnPathSetItemProvider jJnPathSetItemProvider;

	/**
	 * This creates an adapter for a {@link de.fzi.se.controlflowdescription.jjnpaths.JJnPathSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJJnPathSetAdapter() {
		if (jJnPathSetItemProvider == null) {
			jJnPathSetItemProvider = new JJnPathSetItemProvider(this);
		}

		return jJnPathSetItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (jJnPathTestSuiteItemProvider != null) jJnPathTestSuiteItemProvider.dispose();
		if (jJnPathItemProvider != null) jJnPathItemProvider.dispose();
		if (jjPathItemProvider != null) jjPathItemProvider.dispose();
		if (jJnPathTestCaseItemProvider != null) jJnPathTestCaseItemProvider.dispose();
		if (jJnPathsCreationParameterItemProvider != null) jJnPathsCreationParameterItemProvider.dispose();
		if (jJnPathSetItemProvider != null) jJnPathSetItemProvider.dispose();
	}

}
