<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="measurements"
    nsURI="http://sdq.ipd.uka.de/MeasurementsFramework/1.0" nsPrefix="measurements">
  <eClassifiers xsi:type="ecore:EClass" name="VirtualMachineReference" eSuperTypes="#//MachineReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostMachine" ordered="false"
        lowerBound="1" eType="#//PlainMachineReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MachineReference" abstract="true" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainMachineReference" eSuperTypes="#//MachineReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="TaskSet" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootTask" ordered="false"
        lowerBound="1" eType="#//AbstractTask" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="probeSpecRepository" ordered="false"
        eType="ecore:EClass ../../de.uka.ipd.sdq.probespec/model/probespec.ecore#//ProbeSpecRepository"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="machineReferences" ordered="false"
        upperBound="-1" eType="#//MachineReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTask" abstract="true" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceTask" eSuperTypes="#//AbstractTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//AbstractTask" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelTask" eSuperTypes="#//AbstractTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//AbstractTask" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasurementScript">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskSets" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//TaskSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="machineDescriptions" ordered="false"
        upperBound="-1" eType="#//MachineDescription" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MachineDescription" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="machineMappings" ordered="false"
        upperBound="-1" eType="#//MachineMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MachineMapping" eSuperTypes="../../de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="machineReference" ordered="false"
        lowerBound="1" eType="#//MachineReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MachineTask" abstract="true" eSuperTypes="#//AbstractTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="machine" ordered="false"
        lowerBound="1" eType="#//MachineReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopTask" eSuperTypes="#//AbstractTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfIterations" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" ordered="false" lowerBound="1"
        eType="#//AbstractTask" containment="true"/>
  </eClassifiers>
  <eSubpackages name="scheduler" nsURI="http://sdq.ipd.uka.de/MeasurementsFramework/Scheduler/1.0"
      nsPrefix="scheduler">
    <eClassifiers xsi:type="ecore:EEnum" name="ResourceStrategyDemand">
      <eLiterals name="WaitDemand"/>
      <eLiterals name="MandelbrotDemand" value="1"/>
      <eLiterals name="FibonacciDemand" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceStrategyMeasurementTask" eSuperTypes="#//MachineTask">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="demand" ordered="false"
          lowerBound="1" eType="#//scheduler/ResourceStrategyDemand"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParallelProcessTask" eSuperTypes="#//ParallelTask"/>
  </eSubpackages>
</ecore:EPackage>
