<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="completions" nsURI="http://palladiosimulator.org/PCM/Completions/1.0"
    nsPrefix="completions">
  <eClassifiers xsi:type="ecore:EClass" name="Completion" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/ComposedProvidingRequiringEntity platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//repository/ImplementationComponentType"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompletionRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="completions_CompletionRepository"
        ordered="false" upperBound="-1" eType="#//Completion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelegatingExternalCallAction" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//seff/ExternalCallAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkDemandParametricResourceDemand"
      eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//seff/seff_performance/ParametricResourceDemand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredCommunicationLinkResource_ParametricResourceDemand"
        ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//resourcetype/CommunicationLinkResourceType"/>
  </eClassifiers>
</ecore:EPackage>
