/*
* generated by Xtext
*/
package org.palladiosimulator.pcm.pcmstoex;

import org.palladiosimulator.pcm.pcmstoex.PCMStoExStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PCMStoExStandaloneSetup extends PCMStoExStandaloneSetupGenerated{

	public static void doSetup() {
		new PCMStoExStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

