/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.pcm.protocol.validation;


/**
 * A sample validator interface for {@link de.uka.ipd.sdq.pcm.protocol.Protocol}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProtocolValidator {
	boolean validate();

	boolean validateProtocolTypeID(String value);
}
