/**
 * generated by Xtext
 */
package org.palladiosimulator.pcm.pcmstoex.ui.quickfix;

import org.palladiosimulator.commons.stoex.ui.quickfix.StoExQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class PCMStoExQuickfixProvider extends StoExQuickfixProvider {
}
