<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simucom"
    nsURI="http://seq.ipd.uka.de/simucom" nsPrefix="simucom">
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedArchitecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//SimulatedComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//SimulatedMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedMethod">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceEffect" lowerBound="1"
        eType="#//ServiceEffect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceEffect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        eType="ecore:EClass ../../../plugin/org.eclipse.uml2/model/UML2.ecore#//Activity"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedWorld">
    <eStructuralFeatures xsi:type="ecore:EReference" name="architecture" lowerBound="1"
        eType="#//SimulatedArchitecture" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" lowerBound="1" upperBound="-1"
        eType="#//SimulatedUser" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedUser">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        eType="ecore:EClass ../../../plugin/org.eclipse.uml2/model/UML2.ecore#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thinkTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thinkFirst" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
