/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uka.ipd.sdq.pcm.usagemodel.validation;

import de.uka.ipd.sdq.pcm.parameter.VariableUsage;

import de.uka.ipd.sdq.pcm.repository.ProvidedRole;
import de.uka.ipd.sdq.pcm.repository.Signature;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.pcm.usagemodel.EntryLevelSystemCall}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EntryLevelSystemCallValidator {
	boolean validate();

	boolean validateActualParameterUsage_EntryLevelSystemCall(EList<VariableUsage> value);
	boolean validateProvidedRole_EntryLevelSystemCall(ProvidedRole value);
	boolean validateSignature_EntryLevelSystemCall(Signature value);
}
