package edu.kit.ipd.sdq.simcomp.component;

import de.uka.ipd.sdq.pcm.usagemodel.EntryLevelSystemCall;

/**
 * Represents a system simulation component which handles service calls
 * generated by an {@link IWorkload} simulation component.
 * 
 * @author Christoph Föhrdes
 */
public interface ISystem extends ISimulationComponent {

	public void callService(IUser user, EntryLevelSystemCall call);

}
